### ISSUE TITLE
自定义协议栈示例的问题

### ISSUE THREAD

**Issue by Urliuo** [p4gefau1t/trojan-go#153]
照搬 https://p4gefau1t.github.io/trojan-go/advance/customize-protocol-stack/ 的服务端 server.yaml
会得到以下错误：
`github.com/p4gefau1t/trojan-go/proxy.(*Node).LinkNextNode:stack.go:52 invalid redirect address. check your http server: :0 | dial tcp :0: connect: connection refused`

似乎transport层的remote-addr未能传递给trojan，导致trojan的http-check未能正常工作

一个排查问题的方式是用自定义栈来模仿标准的功能。
依个人理解，服务端应该是这样的：

```
run-type: custom

inbound:
  node:

    - protocol: transport
      tag: transport
      config:
        local-addr: 0.0.0.0
        local-port: 443
        remote-addr: 127.0.0.1
        remote-port: 80

    - protocol: tls
      tag: tls
      config:
        ssl:
          sni: localhost
          key: server.key
          cert: server.crt

    - protocol: trojan
      tag: trojan
      config:
        password:
          - 12345678

  path:
    -
      - transport
      - tls
      - trojan

outbound:
  node:
    - protocol: freedom
      tag: freedom

  path:
    -
      - freedom
```

根据实际需求填入具体参数后，同样因上述原因无法正常工作。

如果在trojan层强制忽略http-check或者指定remote-addr，则会引发新的问题，总之无法正常实现网页访问的redirect。
在tls层指定fallback-addr可以触发转发，但仍会报`incoming http request`的error。而且如果设置HTTPS的fallback-port，无论入站是HTTP还是HTTPS，都会返回`plain HTTP request was sent to HTTPS port`。如果设置HTTP的fallback-port，则都会回复自适应的重定向结果。这样都偏离了正常443的行为

不知道这是否属于bug？

如果程序没有问题，还望给出一份经过测试的以自定义栈格式实现原版trojan功能的服务端配置，以帮助理解自定义协议栈的机制
