### ISSUE TITLE
[Feature Request]请求增加 yaml 格式的示例文件

### ISSUE THREAD

**Issue by unknowndev233** [p4gefau1t/trojan-go#165]
只是看到有支持 yaml 但是没有 yaml 的示例文件觉得有点遗憾（在 example 里没有，并且文档中的不够完整）

**Comment by unknowndev233** [comment]
等我看完 yaml 怎么写之后或许可以发一下 pr

**Comment by alinuxsa** [comment]
我试了一下把json转成yaml 启动报错

➜  trojan-go .\trojan-go.exe -config .\client.yaml
[INFO]  2020/08/13 16:26:36 trojan-go v0.7.8 initializing
[FATAL] 2020/08/13 16:26:36 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:37 unknown proxy type:

但是 https://github.com/p4gefau1t/trojan-go/blob/c010e7dda15142a633f43ce74bf8a822f37cd84f/config/config.go#L36
这里有解析yaml的方法,估计是我转的yaml格式哪里不对

**Comment by unknowndev233** [comment]
> 我试了一下把json转成yaml 启动报错
> 
> ➜ trojan-go .\trojan-go.exe -config .\client.yaml
> [INFO] 2020/08/13 16:26:36 trojan-go v0.7.8 initializing
> [FATAL] 2020/08/13 16:26:36 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:37 unknown proxy type:
> 
> 但是
> 
> https://github.com/p4gefau1t/trojan-go/blob/c010e7dda15142a633f43ce74bf8a822f37cd84f/config/config.go#L36
> 
> 
> 这里有解析yaml的方法,估计是我转的yaml格式哪里不对

要不要把文件亮出来看看？

**Comment by alinuxsa** [comment]
> > 我试了一下把json转成yaml 启动报错
> > ➜ trojan-go .\trojan-go.exe -config .\client.yaml
> > [INFO] 2020/08/13 16:26:36 trojan-go v0.7.8 initializing
> > [FATAL] 2020/08/13 16:26:36 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:37 unknown proxy type:
> > 但是
> > https://github.com/p4gefau1t/trojan-go/blob/c010e7dda15142a633f43ce74bf8a822f37cd84f/config/config.go#L36
> > 
> > 这里有解析yaml的方法,估计是我转的yaml格式哪里不对
> 
> 要不要把文件亮出来看看？

```yaml
run_type: client
local_addr: 0.0.0.0
local_port: 1090
remote_addr: 1.2.3.4
remote_port: 443
password:
  - password
ssl:
  sni: sni.com
mux:
  enabled: true
  concurrency: 8
  idle_timeout: 60
router:
  enabled: true
  bypass:
    - geoip:cn
    - geoip:private
    - geosite:cn
    - geosite:geolocation-cn
  block:
    - geosite:category-ads-all
  proxy:
    - geosite:geolocation-!cn
  default_policy: proxy
  geoip: geoip.dat
  geosite: geosite.dat
```
