### ISSUE TITLE
[BUG]tls: bad record MAC

### ISSUE THREAD

**Issue by diyhome** [p4gefau1t/trojan-go#308]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

## 简单描述这个 Bug
之前一直使用正常,直到昨天晚上重启服务器后就开始连接不上,读取其状态信息提示`TLS`相关问题
(服务器有个每天定时重启的任务
## 服务器和客户端环境信息

nginx做前端代理,使用stream分流
* Debian 10 x86_64
* lnmp 1.7
### nginx配置文件
```
stream {
    log_format proxy '$remote_addr [$time_local] '
      '$protocol $status $bytes_sent $bytes_received '
      '$session_time "$upstream_addr" '
      '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';
      access_log /home/wwwlogs/stream-log proxy ;
      open_log_file_cache off;

    map $ssl_preread_server_name $name {
        ppp.domain.com trojan;
        www.domain.com nginx;
    }
    upstream trojan {
        server 127.0.0.1:9443;
    }
    upstream nginx {
        server 127.0.0.1:8443;
    }
    upstream jupyter {
        server 127.0.0.1:2334;
    }
    server {
        listen 443;
        listen [::]:443;
        proxy_pass $name;
        ssl_preread on;
    }
}

```

## 服务端和客户端日志

```
Apr 26 06:55:52 localhost.localdomain trojan-go[873]: [WARN]  2021/04/26 06:55:52 empty tls fallback port
Apr 26 06:55:52 localhost.localdomain trojan-go[873]: [WARN]  2021/04/26 06:55:52 empty tls http response
Apr 26 06:55:53 localhost.localdomain trojan-go[873]: [INFO]  2021/04/26 06:55:53 tcp connection from 127.0.0.1:36490
Apr 26 06:55:53 localhost.localdomain trojan-go[873]: [ERROR] 2021/04/26 06:55:53 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:135 tls handshake failed | local error: tls: bad record MAC
```

### server.yaml
```
run-type: server
local-addr: 127.0.0.1
local-port: 9443
remote-addr: 127.0.0.1
remote-port: 8443
password:
ssl:
  cert: /usr/local/nginx/conf/ssl/domain/fullchain.cer
  key: /usr/local/nginx/conf/ssl/domain/domain.key
fallback-addr: domain
fallback-port: 80
router:
  enable: true
  bypass:
    - geoip:cn
    - geoip:private
    - geosite:cn
    - geosite:geolocation-cn
  block:
    - geosite:category-ads
  proxy:
    - geosite:geolocation-!cn
```

## 服务端和客户端版本信息
```
Trojan-Go v0.8.3
Go Version: go1.16.2
OS/Arch: linux/amd64
Git Commit: 8b01e5122bbcfadfb50a75a09d184798acfa9de7

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:	https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:	https://p4gefau1t.github.io/trojan-go/
```

## 其他信息

你认为对我们修复bug有帮助的任何信息都可以在这里写出来
