### ISSUE TITLE
[Question] 如何配置nginx反向代理wss websocket

### ISSUE THREAD

**Issue by hyhy01** [p4gefau1t/trojan-go#362]
## 服务端和客户端配置文件

```conf
server {
  listen  443 ssl;
  ssl on;
  ssl_certificate       /root/.acme.sh/xxxx/fullchain.cer;
  ssl_certificate_key   /root/.acme.sh/xxx/xxxx.key;
  ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers           HIGH:!aNULL:!MD5;
  server_name           virmachla.hyhy01.virmach;
  ssl_verify_client     off;
        location /ray { # 与 V2Ray 配置中的 path 保持一致
          proxy_redirect off;
          proxy_pass http://127.0.0.1:10087;#假设WebSocket监听在环回地址的10000端口上
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $http_host;

          # Show realip in v2ray access.log
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /ws {
          proxy_redirect off;
          proxy_pass https://127.0.0.1:442;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $http_host;
          proxy_ssl_verify off;
          proxy_ssl_certificate /root/.acme.sh/xxx/fullchain.cer;
          proxy_ssl_certificate_key /root/.acme.sh/xxx/xxx.key;

          # Show realip in v2ray access.log
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```
```conf
run-type: server
local-addr: 0.0.0.0
local-port: 442
remote-addr: 127.0.0.1
remote-port: 80
password:
  - "xx"
ssl:
  cert: /root/.acme.sh/xx/fullchain.cer
  key: /root/.acme.sh/xx/xxx.key
  sni: xx
router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: /root/geoip.dat
  geosite: /root/geosite.dat
websocket:
  enabled: true
  path: "/ws"
  host: "xxxxx"
shadowsocks:
  enabled: true
  method: "AES-128-GCM"
  password: "xxxxx"
```

nginx上面的配置（/ray）是v2ray的，没问题。
下面的配置（/ws）是trojan-go的，nginx报502。trojan-go不经过nginx可以正常使用。
都是通过cdn再到nginx。
nginx应该怎么配？

**Comment by fengqi** [comment]
可以使用 haproxy，sni分流

**Comment by TheBlueKingLP** [comment]
使用`proxy_ssl_name`设定sni域名
```
      proxy_ssl_name $host;
      proxy_ssl_server_name on;
```

```
        location /ws {
          proxy_redirect off;
          proxy_pass https://127.0.0.1:442;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $http_host;
          proxy_ssl_verify off;
          proxy_ssl_certificate /root/.acme.sh/xxx/fullchain.cer;
          proxy_ssl_certificate_key /root/.acme.sh/xxx/xxx.key;

          # Show realip in v2ray access.log
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_ssl_name $host;
          proxy_ssl_server_name on;
        }
```

**Comment by lvii** [comment]
遇到类似的问题 nginx 反向代理转发了客户端的请求，nginx 日志显示请求 **502** 状态码

查看转发到 trojan-go 服务端对应的请求日志：

```
tcp connection from 127.0.0.1:556
failed to perform tls handshake with 127.0.0.1:556, redirecting
| tls: first record does not look like a TLS handshake
```

trojan-go 客户端日志：

```
proxy failed to dial connection
| simplesocks failed to dial using underlying tunnel
| no available mux client found
| mux failed to dial
| websocket failed to handshake with server | bad status
```

`nginx.conf` wss 配置：

``` nginx
location /cdn {
    proxy_redirect off;
    proxy_pass http://127.0.0.1:63012;
    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;

    proxy_ssl_verify off;
    proxy_ssl_certificate /path/.acme.sh/server.com_ecc/fullchain.cer;
    proxy_ssl_certificate_key /path/.acme.sh/server.com_ecc/server.com.key;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_ssl_name $host;
    proxy_ssl_server_name on;
}
```

trojan-go **服务端** 配置：

``` yaml
run-type: server
log-level: 0
local-addr: 0.0.0.0
local-port: 63012
remote-addr: 127.0.0.1
remote-port: 80
password:
  - "xxx"
ssl:
  cert: /path/.acme.sh/server.com_ecc/fullchain.cer
  key: /path/.acme.sh/server.com_ecc/server.com.key
  sni: server.com
router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: /opt/trojan/geoip.dat
  geosite: /opt/trojan/geosite.dat
websocket:
  enabled: true
  path: "/cdn"
  host: "server.com"
```

trojan-go 客户端配置：

```yaml
run-type: client
log-level: 1
local-addr: 127.0.0.1
local-port: 9091
remote-addr: "server.com"
remote-port: 443
password:
  - "xxx"
ssl:
  sni: server.com
mux:
  enabled: true
router:
  enabled: true
  bypass: ['geoip:cn', 'geoip:private', 'geosite:cn', 'geosite:private']
  block: ['geosite:category-ads']
  proxy: ['geosite:geolocation-!cn']
  default_policy: proxy
  geoip: ./geoip.dat
  geosite: ./geosite.dat
websocket:
  enabled: true
  path: "/cdn"
  host: "server.com"
```

感谢！
