### ISSUE TITLE
[BUG] trojan-go忽视配置文件中指定的router下的geoip子项，而认定在执行文件同目录中。

### ISSUE THREAD

**Issue by ghost** [p4gefau1t/trojan-go#375]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

## 简单描述这个 Bug
trojan-go的配置文件：
```yaml
run-type: server
local-addr: "::"
local-port: 443
remote-addr: 127.0.0.1
remote-port: 80
password:
  - ********
ssl:
  cert: /.acme.sh/jiankai.ml/fullchain.cer
  key: /.acme.sh/jiankai.ml/*****.key
  sni: *****
  fallback_port: 1253
router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: /usr/share/trojan-go/geoip.dat
  geosite: /usr/share/trojan-go/geosite.dat
```
其中的geoip与geosite可以指定文件位置。但是运行时，使用journalctl -u trojan-go@config.service查看日志有这一条信息：
```
[ERROR] 2021/08/27 06:41:19 github.com/p4gefau1t/trojan-go/tunnel/router.NewClient:client.go:317 open /usr/bin/geoip.dat: no such file or directory
```

## 如何复现这个 Bug

配置文件指定geoip与geosite文件的位置不同于执行文件所在目录，查看日志，即可发现bug

## 服务器和客户端环境信息
服务器：ubuntu 20.04, linux x86_64, v0.10.4

客户端：此问题与客户端的执行无关，我是在服务器上观察到的bug，只要启动服务即可看到报错，不需要有实际客户端连接。

## 服务端和客户端日志

服务端：[ERROR] 2021/08/27 06:41:19 github.com/p4gefau1t/trojan-go/tunnel/router.NewClient:client.go:317 open /usr/bin/geoip.dat: no such file or directory
客户端：此问题与客户端的执行无关，我是在服务器上观察到的bug，只要启动服务即可看到报错，不需要有实际客户端连接。

## 服务端和客户端配置文件
服务端：
```yaml
run-type: server
local-addr: "::"
local-port: 443
remote-addr: 127.0.0.1
remote-port: 80
password:
  - ********
ssl:
  cert: /.acme.sh/jiankai.ml/fullchain.cer
  key: /.acme.sh/jiankai.ml/*****.key
  sni: *****
  fallback_port: 1253
router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: /usr/share/trojan-go/geoip.dat
  geosite: /usr/share/trojan-go/geosite.dat
```
客户端：此问题与客户端的执行无关，我是在服务器上观察到的bug，只要启动服务即可看到报错，不需要有实际客户端连接。

## 服务端和客户端版本信息

服务端：
Trojan-Go v0.10.4
Go Version: go1.16.4
OS/Arch: linux/amd64
Git Commit: 068d23371c2676212a3399edbabfb2aaedf63750

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:      https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:    https://p4gefau1t.github.io/trojan-go/
客户端：此问题与客户端的执行无关，我是在服务器上观察到的bug，只要启动服务即可看到报错，不需要有实际客户端连接。
## 其他信息

无
