### ISSUE TITLE
[BUG] 填写fallback_port不起作用

### ISSUE THREAD

**Issue by waynon** [p4gefau1t/trojan-go#376]
- [x] **我确定我已经尝试多次复现此次问题，并且将会提供涉及此问题的系统和网络环境，软件及其版本。**

我们建议您按照下方模板填写 Bug Report，以便我们收集更多的有效信息

## 简单描述这个 Bug
填写fallback_port不起作用，日志报错
```
[WARN]  2021/08/27 06:33:43 empty tls fallback port
[WARN]  2021/08/27 06:33:43 empty tls http response
```
我已经搭建了caddy服务器，通过http://example.com:1253 可以访问。

## 如何复现这个 Bug

填写fallback_port字段，发现不起作用，日志报错，http://example.com:443 打开显示未发送任何数据，即ERR_EMPTY_RESPONSE。
我已经搭建了caddy服务器，通过http://example.com:1253 可以访问。

## 服务器和客户端环境信息

服务端：Ubuntu 20.04，x64架构，trojan-go v0.10.4
客户端与该issue无关

## 服务端和客户端日志
服务端：
```
[WARN]  2021/08/27 06:33:43 empty tls fallback port
[WARN]  2021/08/27 06:33:43 empty tls http response
```

## 服务端和客户端配置文件

服务端：
```yaml
run-type: server
local-addr: "::"
local-port: 443
remote-addr: 127.0.0.1
remote-port: 80
password:
  - ********
ssl:
  cert: /.acme.sh/jiankai.ml/fullchain.cer
  key: /.acme.sh/jiankai.ml/*****.key
  sni: *****
  fallback_port: 1253
router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: /usr/share/trojan-go/geoip.dat
  geosite: /usr/share/trojan-go/geosite.dat
```

## 服务端和客户端版本信息

Trojan-Go v0.10.4
Go Version: go1.16.4
OS/Arch: linux/amd64
Git Commit: 068d23371c2676212a3399edbabfb2aaedf63750

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:      https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:    https://p4gefau1t.github.io/trojan-go/

## 其他信息

无

**Comment by waynon** [comment]
在v0.10.5中问题仍然存在，我试了其他端口，都不行

**Comment by tan-kuku** [comment]
在使用 YAML 配置文件的时候，`fallback_port` 需要写成 `fallback-port`。

请参考[Trojan-Go 文档](https://p4gefau1t.github.io/trojan-go/basic/full-config/)：

> Trojan-Go支持对人类更友好的YAML语法，配置文件的基本结构与JSON相同，效果等价。但是为了遵守YAML的命名习惯，你需要把下划线("_")转换为横杠("-")，如`remote_addr`在YAML文件中为`remote-addr`。

**Comment by waynon** [comment]
最后服务端配置改成这样就可以了
```yaml
run-type: server
local-addr: "::"
local-port: 443
remote-addr: 127.0.0.1
remote-port: 80
password:
  - ********
ssl:
  cert: /.acme.sh/jiankai.ml/fullchain.cer
  key: /.acme.sh/jiankai.ml/jiankai.ml.key
  sni: *****
  fallback-port: 80
router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: /usr/share/trojan-go/geoip.dat
  geosite: /usr/share/trojan-go/geosite.dat
```
