### ISSUE TITLE
[BUG] API 动态管理用户失效

### ISSUE THREAD

**Issue by oluceps** [p4gefau1t/trojan-go#441]
## 简单描述 

API用户管理 无法获取:
+ traffic_total  
+ speed_current  

可以正常获取：  
+ speed_limit 
+ hash
+ ip_limit

可以正常set：
+ speed_limit
+ ip_limit  

使用命令 `./trojan-go -api-addr 127.0.0.1:10000 -api get -target-hash <hash> | jq .[]` 返回值：  
```json
{
  "status": {
    "user": {
      "hash": "<hash>"
    },
    "traffic_total": {},
    "speed_current": {},
    "speed_limit": {}
  }
}
```
traffic_total 等数值始终为空，即使用户进行大流量传输。  
尝试过-target-password, 结果没有变化。  

## 环境
测试环境为三台 ` Ubuntu 20.04.4 LTS x86_64` 的vps, 其中一台不使用websocket特性且没有问题，不确定有无相关性

## 服务端配置文件：
```yaml
run-type: server
local-addr: 0.0.0.0
local-port: 8080
remote-addr: "::"
remote-port: 80
log-level: 0
password:
  - passwd

ssl:
  cert: "/home/<>/.acme.sh/fullchain.cer"
  key: "/home/<>/.acme.sh/asdk.key"
  sni: www.domain.com
  alpn:
    - "h2"
    - "http/1.1"

websocket:
  enabled: true
  path: /Hpath
  host: www.domain.com

api:
  enabled: true
  api-addr: 127.0.0.1
  api-port: 10000

router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: ./geoip.dat
  geosite: ./geosite.dat
```

服务端使用nginx + stream 进行 sni 分流，套 websocket 。客户端可以正常连接使用。
[nginx 相关配置](https://gist.github.com/oluceps/b8dc50ace0fc93d29964b3b1128223c7)
## 日志

```
Apr 30 08:52:27 name trojan-go[3189]: [DEBUG] 2022/04/30 08:52:27 github.com/p4gefau1t/trojan-go/api/service.(*ServerAPI).ListUsers:server.go:148 API: ListUsers
```
+ 进行查询操作时，日志中有正常的记录   

## 服务端和客户端版本信息

服务端：
```
Trojan-Go v0.10.6
Go Version: go1.17.1
OS/Arch: linux/amd64
Git Commit: 2dc60f52e79ff8b910e78e444f1e80678e936450

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:	https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:	https://p4gefau1t.github.io/trojan-go/
```
客户端：
```
Trojan-Go v0.10.6
Go Version: go1.17.1
OS/Arch: linux/amd64
Git Commit: 2dc60f52e79ff8b910e78e444f1e80678e936450

Developed by PageFault (p4gefau1t)
Licensed under GNU General Public License version 3
GitHub Repository:	https://github.com/p4gefau1t/trojan-go
Trojan-Go Documents:	https://p4gefau1t.github.io/trojan-go/
```

以及同时使用的V2rayNG、 Clash.Meta、shadowrocket
